from __future__ import annotations

from collections.abc import Sequence
from hashlib import sha256
from typing import Any

import frappe
from frappe.utils import now_datetime

from muster.demo.plan import ScaleProfile, short_id, stable_id

DEFAULT_DATABASE_CHUNK = 500

# These DocTypes are immutable/passive projections with no validation or lifecycle
# controller behavior. Controller-bearing business and approval records deliberately
# stay on Document.insert in the regular seeder.
PASSIVE_DOCTYPES = frozenset(
    {"Muster Work Unit", "Muster Run", "Muster Activity", "Muster Artifact"}
)


def _chunks(values: Sequence[Any], size: int = DEFAULT_DATABASE_CHUNK):
    for start in range(0, len(values), size):
        yield values[start : start + size]


def _standardize(row: dict[str, Any], timestamp: Any) -> dict[str, Any]:
    return {
        "creation": timestamp,
        "modified": timestamp,
        "modified_by": "Administrator",
        "owner": "Administrator",
        "docstatus": 0,
        "idx": 0,
        **row,
    }


def _bulk_insert(doctype: str, rows: list[dict[str, Any]]) -> int:
    if not rows:
        return 0
    if doctype not in PASSIVE_DOCTYPES:
        raise ValueError(f"bulk demo insertion is not approved for {doctype}")
    fields = list(rows[0])
    if any(list(row) != fields for row in rows):
        raise ValueError(f"inconsistent bulk row shape for {doctype}")
    frappe.db.bulk_insert(
        doctype,
        fields,
        ([row[field] for field in fields] for row in rows),
        ignore_duplicates=True,
        chunk_size=DEFAULT_DATABASE_CHUNK,
    )
    return len(rows)


def _existing_by(
    doctype: str,
    missions: list[str],
    fields: list[str],
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for mission_chunk in _chunks(missions):
        rows.extend(
            frappe.get_all(
                doctype,
                filters={"mission": ["in", mission_chunk]},
                fields=fields,
                order_by=None,
            )
        )
    return rows


def _adopt_deterministic_name(doctype: str, current: str, expected: str) -> str:
    """Rename records from the earlier ORM seeder without duplicating projections."""
    if current == expected:
        return current
    if frappe.db.exists(doctype, expected):
        raise ValueError(
            f"cannot normalize {doctype} {current}: deterministic name {expected} already exists"
        )
    if doctype not in PASSIVE_DOCTYPES:
        raise ValueError(f"deterministic demo rename is not approved for {doctype}")
    # These records are passive projections and were originally generated by this
    # seeder. A generic rename_doc scans every Link field in every installed app,
    # which turns a bounded upgrade into O(records × metadata) work. Update the
    # complete, explicit link graph for this private projection family instead.
    table = frappe.qb.DocType(doctype)
    frappe.qb.update(table).set(table.name, expected).where(table.name == current).run()
    if doctype == "Muster Work Unit":
        work_unit = frappe.qb.DocType("Muster Work Unit")
        run = frappe.qb.DocType("Muster Run")
        (
            frappe.qb.update(work_unit)
            .set(work_unit.parent_work_unit, expected)
            .where(work_unit.parent_work_unit == current)
            .run()
        )
        (frappe.qb.update(run).set(run.work_unit, expected).where(run.work_unit == current).run())
    frappe.clear_document_cache(doctype, current)
    frappe.clear_document_cache(doctype, expected)
    return expected


def seed_passive_projections(
    *,
    site: str,
    scenario: str,
    indexed_missions: Sequence[tuple[int, Any]],
    profile: ScaleProfile,
    agents: list[str],
    users: list[str],
) -> dict[str, int]:
    """Materialize high-volume passive proof records in bounded, idempotent batches.

    All names and identity keys derive from the site/scenario/index tuple. Existing
    ORM-created demo rows are adopted by their natural key, so upgrading a previously
    seeded site does not duplicate data.
    """
    if not indexed_missions:
        return {"work_units": 0, "runs": 0, "activities": 0, "artifacts": 0}

    timestamp = now_datetime()
    mission_names = [mission.name for _, mission in indexed_missions]
    existing_units = {
        (row["mission"], row["title"]): row["name"]
        for row in _existing_by("Muster Work Unit", mission_names, ["name", "mission", "title"])
    }
    existing_runs = {
        row["external_run_id"]: row["name"]
        for row in _existing_by("Muster Run", mission_names, ["name", "mission", "external_run_id"])
    }
    existing_activities = {
        row["idempotency_key"]: row["name"]
        for row in _existing_by(
            "Muster Activity", mission_names, ["name", "mission", "idempotency_key"]
        )
    }
    existing_artifacts = {
        (row["mission"], row["checksum"]): row["name"]
        for row in _existing_by("Muster Artifact", mission_names, ["name", "mission", "checksum"])
    }

    unit_rows: list[dict[str, Any]] = []
    run_rows: list[dict[str, Any]] = []
    activity_rows: list[dict[str, Any]] = []
    artifact_rows: list[dict[str, Any]] = []
    event_types = (
        "mission.planned",
        "work_unit.started",
        "tool.preflighted",
        "change.proposed",
        "approval.checked",
        "evidence.attached",
        "postcondition.verified",
        "mission.progressed",
    )
    artifact_kinds = ("Report", "PDF", "Spreadsheet", "Presentation", "Receipt")

    for mission_index, mission in indexed_missions:
        parent_name: str | None = None
        for unit_index in range(profile.work_units_per_mission):
            title = f"[Muster Demo] M{mission_index + 1:04d} Work {unit_index + 1:02d}"
            natural_key = (mission.name, title)
            expected_unit_name = "muster-demo-unit-" + short_id(
                site, scenario, "work-unit", f"{mission_index}:{unit_index}"
            )
            unit_name = existing_units.get(natural_key) or expected_unit_name
            if natural_key in existing_units:
                unit_name = _adopt_deterministic_name(
                    "Muster Work Unit", unit_name, expected_unit_name
                )
                existing_units[natural_key] = unit_name
            if natural_key not in existing_units:
                unit_rows.append(
                    _standardize(
                        {
                            "name": unit_name,
                            "title": title,
                            "mission": mission.name,
                            "status": ("Succeeded" if mission.status == "Completed" else "Running"),
                            "parent_work_unit": parent_name,
                            "tree_path": f"/{mission_index:04d}/{unit_index:02d}",
                            "depth": min(unit_index, 3),
                            "agent": agents[(mission_index + unit_index) % len(agents)],
                            "target_workspace": "Muster Mission Control",
                            "dependencies_json": frappe.as_json(
                                [parent_name] if parent_name else []
                            ),
                            "attempt_count": 1 + int(unit_index % 7 == 0),
                            "started_at": timestamp,
                        },
                        timestamp,
                    )
                )
                existing_units[natural_key] = unit_name
            parent_name = unit_name

            external_id = stable_id(site, scenario, "run", f"{mission_index}:{unit_index}")
            expected_run_name = "muster-demo-run-" + short_id(
                site, scenario, "run-name", external_id
            )
            if external_id in existing_runs:
                existing_runs[external_id] = _adopt_deterministic_name(
                    "Muster Run", existing_runs[external_id], expected_run_name
                )
            if external_id not in existing_runs:
                run_rows.append(
                    _standardize(
                        {
                            "name": expected_run_name,
                            "external_run_id": external_id,
                            "mission": mission.name,
                            "work_unit": unit_name,
                            "attempt": 1,
                            "status": ("Succeeded" if mission.status == "Completed" else "Running"),
                            "execution_user": users[mission_index % len(users)],
                            "job_id": "muster-demo-" + short_id(site, scenario, "job", external_id),
                            "started_at": timestamp,
                            "heartbeat_at": timestamp,
                            "cursor": unit_index,
                            "usage_json": frappe.as_json({"tool_calls": unit_index % 5}),
                            "result_json": frappe.as_json({"demo": True, "redacted": True}),
                        },
                        timestamp,
                    )
                )
                existing_runs[external_id] = expected_run_name

        actor = users[mission_index % len(users)]
        for event_index in range(profile.activities_per_mission):
            idempotency_key = stable_id(
                site, scenario, "activity", f"{mission_index}:{event_index}"
            )
            expected_activity_name = "muster-demo-activity-" + short_id(
                site, scenario, "activity-name", idempotency_key
            )
            if idempotency_key in existing_activities:
                existing_activities[idempotency_key] = _adopt_deterministic_name(
                    "Muster Activity",
                    existing_activities[idempotency_key],
                    expected_activity_name,
                )
                continue
            activity_rows.append(
                _standardize(
                    {
                        "name": expected_activity_name,
                        "mission": mission.name,
                        "sequence": event_index + 1,
                        "event_type": event_types[event_index % len(event_types)],
                        "state": mission.status,
                        "summary": (
                            f"Demo evidence event {event_index + 1:02d}: permission-filtered "
                            "work remained inside the approved plan."
                        ),
                        "visibility": "Participants",
                        "actor": actor,
                        "idempotency_key": idempotency_key,
                        "payload_json": frappe.as_json(
                            {
                                "demo": True,
                                "mission_index": mission_index,
                                "event_index": event_index,
                                "contains_secrets": False,
                            }
                        ),
                    },
                    timestamp,
                )
            )
            existing_activities[idempotency_key] = expected_activity_name

        for artifact_index in range(profile.artifacts_per_mission):
            checksum = sha256(
                f"{site}|{scenario}|artifact|{mission_index}|{artifact_index}".encode()
            ).hexdigest()
            natural_key = (mission.name, checksum)
            expected_artifact_name = "muster-demo-artifact-" + short_id(
                site, scenario, "artifact-name", checksum
            )
            if natural_key in existing_artifacts:
                existing_artifacts[natural_key] = _adopt_deterministic_name(
                    "Muster Artifact",
                    existing_artifacts[natural_key],
                    expected_artifact_name,
                )
                continue
            artifact_rows.append(
                _standardize(
                    {
                        "name": expected_artifact_name,
                        "title": (
                            f"[Muster Demo] Evidence {mission_index + 1:04d}-"
                            f"{artifact_index + 1:02d}"
                        ),
                        "mission": mission.name,
                        "kind": artifact_kinds[artifact_index % len(artifact_kinds)],
                        "visibility": "Participants",
                        "is_public": 0,
                        "reference_doctype": "Muster Mission",
                        "reference_name": mission.name,
                        "mime_type": "application/json",
                        "size_bytes": 256 + artifact_index,
                        "checksum": checksum,
                        "verification_status": "Verified",
                        "verified_at": timestamp,
                    },
                    timestamp,
                )
            )
            existing_artifacts[natural_key] = expected_artifact_name

    return {
        "work_units": _bulk_insert("Muster Work Unit", unit_rows),
        "runs": _bulk_insert("Muster Run", run_rows),
        "activities": _bulk_insert("Muster Activity", activity_rows),
        "artifacts": _bulk_insert("Muster Artifact", artifact_rows),
    }
